<?xml version="1.0" encoding="utf-8"?><Database Name="GestionFestival" Class="DataContextDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=DESKTOP-73L8O8A;Initial Catalog=GestionFestival;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="GestionFestivalConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Administrateur" Member="Administrateur">
    <Type Name="Administrateur">
      <Column Name="idPers" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="dateFest" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="nomFest" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Administrateur_Responsable" Member="Responsable" ThisKey="idPers" OtherKey="idAdmin" Type="Responsable" />
      <Association Name="Personnel_Administrateur" Member="Personnel" ThisKey="idPers" OtherKey="idPers" Type="Personnel" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Comptable" Member="Comptable">
    <Type Name="Comptable">
      <Column Name="idPers" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="budgetDisp" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Association Name="Comptable_Poste" Member="Poste" ThisKey="idPers" OtherKey="idComptable" Type="Poste" />
      <Association Name="Personnel_Comptable" Member="Personnel" ThisKey="idPers" OtherKey="idPers" Type="Personnel" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Personnel" Member="Personnel">
    <Type Name="Personnel">
      <Column Name="idPers" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="nomPers" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="prenomPers" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="dateNaiss" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="email" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="telephone" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="specialisation" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="password" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Personnel_Administrateur" Member="Administrateur" ThisKey="idPers" OtherKey="idPers" Type="Administrateur" Cardinality="One" />
      <Association Name="Personnel_Comptable" Member="Comptable" ThisKey="idPers" OtherKey="idPers" Type="Comptable" Cardinality="One" />
      <Association Name="Personnel_Participant" Member="Participant" ThisKey="idPers" OtherKey="idPers" Type="Participant" Cardinality="One" />
      <Association Name="Personnel_Responsable" Member="Responsable" ThisKey="idPers" OtherKey="idPers" Type="Responsable" Cardinality="One" />
    </Type>
  </Table>
  <Table Name="dbo.Depense" Member="Depense">
    <Type Name="Depense">
      <Column Name="idDepense" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="totalDep" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="idPoste" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Depense_Materiel" Member="Materiel" ThisKey="idDepense" OtherKey="idDepense" Type="Materiel" />
      <Association Name="Depense_Participant" Member="Participant" ThisKey="idDepense" OtherKey="idDepense" Type="Participant" />
      <Association Name="Poste_Depense" Member="Poste" ThisKey="idPoste" OtherKey="idPoste" Type="Poste" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Materiel" Member="Materiel">
    <Type Name="Materiel">
      <Column Name="idMateriel" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="prix" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="quantité" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="idDepense" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="idPers" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Depense_Materiel" Member="Depense" ThisKey="idDepense" OtherKey="idDepense" Type="Depense" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Participant" Member="Participant">
    <Type Name="Participant">
      <Column Name="idPers" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="heureTravail" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="salaire" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="idResp" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="idDepense" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Depense_Participant" Member="Depense" ThisKey="idDepense" OtherKey="idDepense" Type="Depense" IsForeignKey="true" />
      <Association Name="Personnel_Participant" Member="Personnel" ThisKey="idPers" OtherKey="idPers" Type="Personnel" IsForeignKey="true" />
      <Association Name="Responsable_Participant" Member="Responsable" ThisKey="idResp" OtherKey="idPers" Type="Responsable" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Poste" Member="Poste">
    <Type Name="Poste">
      <Column Name="idPoste" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="nomPoste" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="description" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="idComptable" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Poste_Depense" Member="Depense" ThisKey="idPoste" OtherKey="idPoste" Type="Depense" />
      <Association Name="Poste_Recette" Member="Recette" ThisKey="idPoste" OtherKey="idPoste" Type="Recette" />
      <Association Name="Poste_Responsable" Member="Responsable" ThisKey="idPoste" OtherKey="idPoste" Type="Responsable" />
      <Association Name="Comptable_Poste" Member="Comptable" ThisKey="idComptable" OtherKey="idPers" Type="Comptable" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Recette" Member="Recette">
    <Type Name="Recette">
      <Column Name="idRecette" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="totalRec" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="idPoste" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Recette_Revenu" Member="Revenu" ThisKey="idRecette" OtherKey="idRecette" Type="Revenu" />
      <Association Name="Poste_Recette" Member="Poste" ThisKey="idPoste" OtherKey="idPoste" Type="Poste" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Responsable" Member="Responsable">
    <Type Name="Responsable">
      <Column Name="idPers" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="fonction" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="salaireResp" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="idPoste" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="idAdmin" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Responsable_Participant" Member="Participant" ThisKey="idPers" OtherKey="idResp" Type="Participant" />
      <Association Name="Responsable_Revenu" Member="Revenu" ThisKey="idPers" OtherKey="idPersonnel" Type="Revenu" />
      <Association Name="Administrateur_Responsable" Member="Administrateur" ThisKey="idAdmin" OtherKey="idPers" Type="Administrateur" IsForeignKey="true" />
      <Association Name="Personnel_Responsable" Member="Personnel" ThisKey="idPers" OtherKey="idPers" Type="Personnel" IsForeignKey="true" />
      <Association Name="Poste_Responsable" Member="Poste" ThisKey="idPoste" OtherKey="idPoste" Type="Poste" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Revenu" Member="Revenu">
    <Type Name="Revenu">
      <Column Name="idRevenu" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="description" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="montant" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="idRecette" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="idPersonnel" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Recette_Revenu" Member="Recette" ThisKey="idRecette" OtherKey="idRecette" Type="Recette" IsForeignKey="true" />
      <Association Name="Responsable_Revenu" Member="Responsable" ThisKey="idPersonnel" OtherKey="idPers" Type="Responsable" IsForeignKey="true" />
    </Type>
  </Table>
  <Function Name="dbo.VérificationLogin" Method="VérificationLogin">
    <Parameter Name="email" Type="System.String" DbType="NVarChar(30)" />
    <Parameter Name="pass" Type="System.String" DbType="NVarChar(20)" />
    <ElementType Name="VérificationLoginResult">
      <Column Name="idPers" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="nomPers" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="prenomPers" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="dateNaiss" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="email" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="telephone" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="specialisation" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="password" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
</Database>