<?xml version="1.0" encoding="utf-8"?><Database Name="GestionFestival" Class="DataContextDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=DESKTOP-73L8O8A;Initial Catalog=GestionFestival;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="GestionFestivalConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Demande" Member="Demande">
    <Type Name="Demande">
      <Column Name="idDemande" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="montant" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="dateDemande" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="idPersonnel" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Personnel_Demande" Member="Personnel" ThisKey="idPersonnel" OtherKey="idPersonnel" Type="Personnel" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Festival" Member="Festival">
    <Type Name="Festival">
      <Column Name="idFestival" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="nomFest" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="dateDebut" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="dateFin" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="budget" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Association Name="Festival_Personnel" Member="Personnel" ThisKey="idFestival" OtherKey="idFestival" Type="Personnel" />
    </Type>
  </Table>
  <Table Name="dbo.Materiel" Member="Materiel">
    <Type Name="Materiel">
      <Column Name="idMateriel" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nom" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="prix" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="quantité" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="idPoste" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Poste_Materiel" Member="Poste" ThisKey="idPoste" OtherKey="idPoste" Type="Poste" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Personnel" Member="Personnel">
    <Type Name="Personnel">
      <Column Name="idPersonnel" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nomPersonnel" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="prenomPersonnel" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="dateNaissance" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="email" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="telephone" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="specialisation" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="password" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="libelRole" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="idPoste" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="idFestival" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Personnel_Demande" Member="Demande" ThisKey="idPersonnel" OtherKey="idPersonnel" Type="Demande" />
      <Association Name="Personnel_Salaire" Member="Salaire" ThisKey="idPersonnel" OtherKey="idPersonnel" Type="Salaire" />
      <Association Name="Festival_Personnel" Member="Festival" ThisKey="idFestival" OtherKey="idFestival" Type="Festival" IsForeignKey="true" />
      <Association Name="Poste_Personnel" Member="Poste" ThisKey="idPoste" OtherKey="idPoste" Type="Poste" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Revenu" Member="Revenu">
    <Type Name="Revenu">
      <Column Name="idRevenu" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="description" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="montant" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="idPoste" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Poste_Revenu" Member="Poste" ThisKey="idPoste" OtherKey="idPoste" Type="Poste" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Poste" Member="Poste">
    <Type Name="Poste">
      <Column Name="idPoste" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nomPoste" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="description" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="budgetDepart" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="budgetActuel" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="idFestival" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Poste_Materiel" Member="Materiel" ThisKey="idPoste" OtherKey="idPoste" Type="Materiel" />
      <Association Name="Poste_Personnel" Member="Personnel" ThisKey="idPoste" OtherKey="idPoste" Type="Personnel" />
      <Association Name="Poste_Revenu" Member="Revenu" ThisKey="idPoste" OtherKey="idPoste" Type="Revenu" />
    </Type>
  </Table>
  <Table Name="dbo.Salaire" Member="Salaire">
    <Type Name="Salaire">
      <Column Name="idSalaire" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="salaireHoraire" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="nbrHeure" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="idPersonnel" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Personnel_Salaire" Member="Personnel" ThisKey="idPersonnel" OtherKey="idPersonnel" Type="Personnel" IsForeignKey="true" />
    </Type>
  </Table>
  <Function Name="dbo.AfficherPoste" Method="AfficherPoste">
    <ElementType Name="AfficherPosteResult">
      <Column Name="idPoste" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="nomPoste" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="description" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="budgetDepart" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="budgetActuel" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="idFestival" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.AjouterMateriel" Method="AjouterMateriel">
    <Parameter Name="nom" Type="System.String" DbType="NVarChar(20)" />
    <Parameter Name="prix" Type="System.Decimal" DbType="Money" />
    <Parameter Name="qtt" Type="System.Int32" DbType="Int" />
    <Parameter Name="idPoste" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.AjouterPersonnel" Method="AjouterPersonnel">
    <Parameter Name="nom" Type="System.String" DbType="NVarChar(20)" />
    <Parameter Name="prenom" Type="System.String" DbType="NVarChar(20)" />
    <Parameter Name="dateNaiss" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="email" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="tel" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="spec" Type="System.String" DbType="NVarChar(20)" />
    <Parameter Name="pass" Type="System.String" DbType="NVarChar(20)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.AjouterPoste" Method="AjouterPoste">
    <Parameter Name="nomPoste" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="description" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.AjouterRevenu" Method="AjouterRevenu">
    <Parameter Name="desc" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="montant" Type="System.Decimal" DbType="Money" />
    <Parameter Name="idPoste" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.DeleteMateriel" Method="DeleteMateriel">
    <Parameter Name="idMat" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.DeleteRevenu" Method="DeleteRevenu">
    <Parameter Name="idRev" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.GetAllMateriel" Method="GetAllMateriel">
    <Parameter Name="idPoste" Type="System.Int32" DbType="Int" />
    <ElementType Name="GetAllMaterielResult">
      <Column Name="idMateriel" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="nom" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="prix" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="quantité" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="idPoste" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetAllRevenu" Method="GetAllRevenu">
    <Parameter Name="idPoste" Type="System.Int32" DbType="Int" />
    <ElementType Name="GetAllRevenuResult">
      <Column Name="idRevenu" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="description" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="montant" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="idPoste" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetPersonnelOnly" Method="GetPersonnelOnly">
    <ElementType Name="GetPersonnelOnlyResult">
      <Column Name="idPersonnel" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="nomPersonnel" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="prenomPersonnel" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="dateNaissance" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="email" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="telephone" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="specialisation" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="password" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="libelRole" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="idPoste" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="idFestival" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetRespAndPoste" Method="GetRespAndPoste">
    <Parameter Name="idPers" Type="System.Int32" DbType="Int" />
    <ElementType Name="GetRespAndPosteResult">
      <Column Name="idPersonnel" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="nomPersonnel" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="prenomPersonnel" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="dateNaissance" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="email" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="telephone" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="specialisation" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="password" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="libelRole" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="idPoste" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="idFestival" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="idPoste1" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="nomPoste" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="description" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="budgetDepart" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="budgetActuel" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="idFestival1" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetSalaire" Method="GetSalaire">
    <Parameter Name="idPers" Type="System.Int32" DbType="Int" />
    <ElementType Name="GetSalaireResult">
      <Column Name="idSalaire" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="salaireHoraire" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="nbrHeure" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="idPersonnel" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.ModifierPoste" Method="ModifierPoste">
    <Parameter Name="id" Type="System.Int32" DbType="Int" />
    <Parameter Name="nomPoste" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="description" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SupprimerPoste" Method="SupprimerPoste">
    <Parameter Name="idPoste" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.UpdateMateriel" Method="UpdateMateriel">
    <Parameter Name="nom" Type="System.String" DbType="NVarChar(20)" />
    <Parameter Name="prix" Type="System.Decimal" DbType="Money" />
    <Parameter Name="qtt" Type="System.Int32" DbType="Int" />
    <Parameter Name="idMat" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.UpdateParticipant" Method="UpdateParticipant">
    <Parameter Name="salaire" Type="System.Decimal" DbType="Money" />
    <Parameter Name="ht" Type="System.Int32" DbType="Int" />
    <Parameter Name="idPers" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.UpdateRevenu" Method="UpdateRevenu">
    <Parameter Name="desc" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="montant" Type="System.Decimal" DbType="Money" />
    <Parameter Name="idRev" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.VérificatioCompteExistant" Method="VérificatioCompteExistant">
    <Parameter Name="email" Type="System.String" DbType="NVarChar(50)" />
    <ElementType Name="VérificatioCompteExistantResult">
      <Column Name="" Member="Column1" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.VérificationLogin" Method="VérificationLogin">
    <Parameter Name="email" Type="System.String" DbType="NVarChar(30)" />
    <Parameter Name="pass" Type="System.String" DbType="NVarChar(50)" />
    <ElementType Name="VérificationLoginResult">
      <Column Name="idPersonnel" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="nomPersonnel" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="prenomPersonnel" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="dateNaissance" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="email" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="telephone" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="specialisation" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="password" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="libelRole" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="idPoste" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="idFestival" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.AjouterParticipant" Method="AjouterParticipant">
    <Parameter Name="idPers" Type="System.Int32" DbType="Int" />
    <Parameter Name="salaire" Type="System.Decimal" DbType="Money" />
    <Parameter Name="ht" Type="System.Int32" DbType="Int" />
    <Parameter Name="idPoste" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.GetAllParticipant" Method="GetAllParticipant">
    <Parameter Name="idPoste" Type="System.Int32" DbType="Int" />
    <ElementType Name="GetAllParticipantResult">
      <Column Name="idPersonnel" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="nomPersonnel" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="prenomPersonnel" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="dateNaissance" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="email" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="telephone" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="specialisation" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="password" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="libelRole" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="idPoste" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="idFestival" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="idSalaire" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="salaireHoraire" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="nbrHeure" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="idPersonnel1" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.DeleteParticipant" Method="DeleteParticipant">
    <Parameter Name="idPers" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
</Database>