#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gestionFestival.DAL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="GestionFestival")]
	public partial class DataContextDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Définitions de méthodes d'extensibilité
    partial void OnCreated();
    partial void InsertDemande(Demande instance);
    partial void UpdateDemande(Demande instance);
    partial void DeleteDemande(Demande instance);
    partial void InsertFestival(Festival instance);
    partial void UpdateFestival(Festival instance);
    partial void DeleteFestival(Festival instance);
    partial void InsertMateriel(Materiel instance);
    partial void UpdateMateriel(Materiel instance);
    partial void DeleteMateriel(Materiel instance);
    partial void InsertPersonnel(Personnel instance);
    partial void UpdatePersonnel(Personnel instance);
    partial void DeletePersonnel(Personnel instance);
    partial void InsertPoste(Poste instance);
    partial void UpdatePoste(Poste instance);
    partial void DeletePoste(Poste instance);
    partial void InsertRevenu(Revenu instance);
    partial void UpdateRevenu(Revenu instance);
    partial void DeleteRevenu(Revenu instance);
    partial void InsertSalaire(Salaire instance);
    partial void UpdateSalaire(Salaire instance);
    partial void DeleteSalaire(Salaire instance);
    #endregion
		
		public DataContextDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["GestionFestivalConnectionString1"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataContextDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataContextDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataContextDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataContextDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Demande> Demande
		{
			get
			{
				return this.GetTable<Demande>();
			}
		}
		
		public System.Data.Linq.Table<Festival> Festival
		{
			get
			{
				return this.GetTable<Festival>();
			}
		}
		
		public System.Data.Linq.Table<Materiel> Materiel
		{
			get
			{
				return this.GetTable<Materiel>();
			}
		}
		
		public System.Data.Linq.Table<Personnel> Personnel
		{
			get
			{
				return this.GetTable<Personnel>();
			}
		}
		
		public System.Data.Linq.Table<Poste> Poste
		{
			get
			{
				return this.GetTable<Poste>();
			}
		}
		
		public System.Data.Linq.Table<Revenu> Revenu
		{
			get
			{
				return this.GetTable<Revenu>();
			}
		}
		
		public System.Data.Linq.Table<Salaire> Salaire
		{
			get
			{
				return this.GetTable<Salaire>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.AfficherPoste")]
		public ISingleResult<AfficherPosteResult> AfficherPoste()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<AfficherPosteResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.AjouterMateriel")]
		public int AjouterMateriel([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(20)")] string nom, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Money")] System.Nullable<decimal> prix, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> qtt, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idPoste)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nom, prix, qtt, idPoste);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.AjouterParticipant")]
		public int AjouterParticipant([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idPers, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Money")] System.Nullable<decimal> salaire, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> ht, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idPoste)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idPers, salaire, ht, idPoste);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.AjouterPersonnel")]
		public int AjouterPersonnel([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(20)")] string nom, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(20)")] string prenom, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> dateNaiss, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string email, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string tel, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(20)")] string spec, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(20)")] string pass)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nom, prenom, dateNaiss, email, tel, spec, pass);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.AjouterPoste")]
		public int AjouterPoste([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string nomPoste, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string description)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nomPoste, description);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.AjouterRevenu")]
		public int AjouterRevenu([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string desc, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Money")] System.Nullable<decimal> montant, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idPoste)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), desc, montant, idPoste);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.DeleteMateriel")]
		public int DeleteMateriel([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idMat)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idMat);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.DeleteParticipant")]
		public int DeleteParticipant([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idPers)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idPers);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.DeleteRevenu")]
		public int DeleteRevenu([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idRev)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idRev);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetAllMateriel")]
		public ISingleResult<GetAllMaterielResult> GetAllMateriel([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idPoste)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idPoste);
			return ((ISingleResult<GetAllMaterielResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetAllParticipant")]
		public ISingleResult<GetAllParticipantResult> GetAllParticipant([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idPoste)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idPoste);
			return ((ISingleResult<GetAllParticipantResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetAllRevenu")]
		public ISingleResult<GetAllRevenuResult> GetAllRevenu([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idPoste)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idPoste);
			return ((ISingleResult<GetAllRevenuResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetPersonnelOnly")]
		public ISingleResult<GetPersonnelOnlyResult> GetPersonnelOnly()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<GetPersonnelOnlyResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetRespAndPoste")]
		public ISingleResult<GetRespAndPosteResult> GetRespAndPoste([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idPers)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idPers);
			return ((ISingleResult<GetRespAndPosteResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetSalaire")]
		public ISingleResult<GetSalaireResult> GetSalaire([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idPers)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idPers);
			return ((ISingleResult<GetSalaireResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ModifierPoste")]
		public int ModifierPoste([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string nomPoste, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string description)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, nomPoste, description);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SupprimerPoste")]
		public int SupprimerPoste([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idPoste)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idPoste);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.UpdateMateriel")]
		public int UpdateMateriel([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(20)")] string nom, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Money")] System.Nullable<decimal> prix, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> qtt, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idMat)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nom, prix, qtt, idMat);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.UpdateParticipant")]
		public int UpdateParticipant([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Money")] System.Nullable<decimal> salaire, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> ht, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idPers)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), salaire, ht, idPers);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.UpdateRevenu")]
		public int UpdateRevenu([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string desc, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Money")] System.Nullable<decimal> montant, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idRev)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), desc, montant, idRev);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.VérificatioCompteExistant")]
		public ISingleResult<VérificatioCompteExistantResult> VérificatioCompteExistant([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string email)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), email);
			return ((ISingleResult<VérificatioCompteExistantResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.VérificationLogin")]
		public ISingleResult<VérificationLoginResult> VérificationLogin([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(30)")] string email, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string pass)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), email, pass);
			return ((ISingleResult<VérificationLoginResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Demande")]
	public partial class Demande : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idDemande;
		
		private decimal _montant;
		
		private System.DateTime _dateDemande;
		
		private int _idPersonnel;
		
		private EntityRef<Personnel> _Personnel;
		
    #region Définitions de méthodes d'extensibilité
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidDemandeChanging(int value);
    partial void OnidDemandeChanged();
    partial void OnmontantChanging(decimal value);
    partial void OnmontantChanged();
    partial void OndateDemandeChanging(System.DateTime value);
    partial void OndateDemandeChanged();
    partial void OnidPersonnelChanging(int value);
    partial void OnidPersonnelChanged();
    #endregion
		
		public Demande()
		{
			this._Personnel = default(EntityRef<Personnel>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idDemande", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idDemande
		{
			get
			{
				return this._idDemande;
			}
			set
			{
				if ((this._idDemande != value))
				{
					this.OnidDemandeChanging(value);
					this.SendPropertyChanging();
					this._idDemande = value;
					this.SendPropertyChanged("idDemande");
					this.OnidDemandeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_montant", DbType="Money NOT NULL")]
		public decimal montant
		{
			get
			{
				return this._montant;
			}
			set
			{
				if ((this._montant != value))
				{
					this.OnmontantChanging(value);
					this.SendPropertyChanging();
					this._montant = value;
					this.SendPropertyChanged("montant");
					this.OnmontantChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dateDemande", DbType="DateTime NOT NULL")]
		public System.DateTime dateDemande
		{
			get
			{
				return this._dateDemande;
			}
			set
			{
				if ((this._dateDemande != value))
				{
					this.OndateDemandeChanging(value);
					this.SendPropertyChanging();
					this._dateDemande = value;
					this.SendPropertyChanged("dateDemande");
					this.OndateDemandeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idPersonnel", DbType="Int NOT NULL")]
		public int idPersonnel
		{
			get
			{
				return this._idPersonnel;
			}
			set
			{
				if ((this._idPersonnel != value))
				{
					if (this._Personnel.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidPersonnelChanging(value);
					this.SendPropertyChanging();
					this._idPersonnel = value;
					this.SendPropertyChanged("idPersonnel");
					this.OnidPersonnelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Personnel_Demande", Storage="_Personnel", ThisKey="idPersonnel", OtherKey="idPersonnel", IsForeignKey=true)]
		public Personnel Personnel
		{
			get
			{
				return this._Personnel.Entity;
			}
			set
			{
				Personnel previousValue = this._Personnel.Entity;
				if (((previousValue != value) 
							|| (this._Personnel.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Personnel.Entity = null;
						previousValue.Demande.Remove(this);
					}
					this._Personnel.Entity = value;
					if ((value != null))
					{
						value.Demande.Add(this);
						this._idPersonnel = value.idPersonnel;
					}
					else
					{
						this._idPersonnel = default(int);
					}
					this.SendPropertyChanged("Personnel");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Festival")]
	public partial class Festival : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idFestival;
		
		private string _nomFest;
		
		private System.DateTime _dateDebut;
		
		private System.DateTime _dateFin;
		
		private decimal _budget;
		
		private EntitySet<Personnel> _Personnel;
		
    #region Définitions de méthodes d'extensibilité
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidFestivalChanging(int value);
    partial void OnidFestivalChanged();
    partial void OnnomFestChanging(string value);
    partial void OnnomFestChanged();
    partial void OndateDebutChanging(System.DateTime value);
    partial void OndateDebutChanged();
    partial void OndateFinChanging(System.DateTime value);
    partial void OndateFinChanged();
    partial void OnbudgetChanging(decimal value);
    partial void OnbudgetChanged();
    #endregion
		
		public Festival()
		{
			this._Personnel = new EntitySet<Personnel>(new Action<Personnel>(this.attach_Personnel), new Action<Personnel>(this.detach_Personnel));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idFestival", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int idFestival
		{
			get
			{
				return this._idFestival;
			}
			set
			{
				if ((this._idFestival != value))
				{
					this.OnidFestivalChanging(value);
					this.SendPropertyChanging();
					this._idFestival = value;
					this.SendPropertyChanged("idFestival");
					this.OnidFestivalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nomFest", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string nomFest
		{
			get
			{
				return this._nomFest;
			}
			set
			{
				if ((this._nomFest != value))
				{
					this.OnnomFestChanging(value);
					this.SendPropertyChanging();
					this._nomFest = value;
					this.SendPropertyChanged("nomFest");
					this.OnnomFestChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dateDebut", DbType="DateTime NOT NULL")]
		public System.DateTime dateDebut
		{
			get
			{
				return this._dateDebut;
			}
			set
			{
				if ((this._dateDebut != value))
				{
					this.OndateDebutChanging(value);
					this.SendPropertyChanging();
					this._dateDebut = value;
					this.SendPropertyChanged("dateDebut");
					this.OndateDebutChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dateFin", DbType="DateTime NOT NULL")]
		public System.DateTime dateFin
		{
			get
			{
				return this._dateFin;
			}
			set
			{
				if ((this._dateFin != value))
				{
					this.OndateFinChanging(value);
					this.SendPropertyChanging();
					this._dateFin = value;
					this.SendPropertyChanged("dateFin");
					this.OndateFinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_budget", DbType="Money NOT NULL")]
		public decimal budget
		{
			get
			{
				return this._budget;
			}
			set
			{
				if ((this._budget != value))
				{
					this.OnbudgetChanging(value);
					this.SendPropertyChanging();
					this._budget = value;
					this.SendPropertyChanged("budget");
					this.OnbudgetChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Festival_Personnel", Storage="_Personnel", ThisKey="idFestival", OtherKey="idFestival")]
		public EntitySet<Personnel> Personnel
		{
			get
			{
				return this._Personnel;
			}
			set
			{
				this._Personnel.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Personnel(Personnel entity)
		{
			this.SendPropertyChanging();
			entity.Festival = this;
		}
		
		private void detach_Personnel(Personnel entity)
		{
			this.SendPropertyChanging();
			entity.Festival = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Materiel")]
	public partial class Materiel : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idMateriel;
		
		private string _nom;
		
		private decimal _prix;
		
		private int _quantité;
		
		private int _idPoste;
		
		private EntityRef<Poste> _Poste;
		
    #region Définitions de méthodes d'extensibilité
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidMaterielChanging(int value);
    partial void OnidMaterielChanged();
    partial void OnnomChanging(string value);
    partial void OnnomChanged();
    partial void OnprixChanging(decimal value);
    partial void OnprixChanged();
    partial void OnquantitéChanging(int value);
    partial void OnquantitéChanged();
    partial void OnidPosteChanging(int value);
    partial void OnidPosteChanged();
    #endregion
		
		public Materiel()
		{
			this._Poste = default(EntityRef<Poste>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idMateriel", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idMateriel
		{
			get
			{
				return this._idMateriel;
			}
			set
			{
				if ((this._idMateriel != value))
				{
					this.OnidMaterielChanging(value);
					this.SendPropertyChanging();
					this._idMateriel = value;
					this.SendPropertyChanged("idMateriel");
					this.OnidMaterielChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nom", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string nom
		{
			get
			{
				return this._nom;
			}
			set
			{
				if ((this._nom != value))
				{
					this.OnnomChanging(value);
					this.SendPropertyChanging();
					this._nom = value;
					this.SendPropertyChanged("nom");
					this.OnnomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_prix", DbType="Money NOT NULL")]
		public decimal prix
		{
			get
			{
				return this._prix;
			}
			set
			{
				if ((this._prix != value))
				{
					this.OnprixChanging(value);
					this.SendPropertyChanging();
					this._prix = value;
					this.SendPropertyChanged("prix");
					this.OnprixChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_quantité", DbType="Int NOT NULL")]
		public int quantité
		{
			get
			{
				return this._quantité;
			}
			set
			{
				if ((this._quantité != value))
				{
					this.OnquantitéChanging(value);
					this.SendPropertyChanging();
					this._quantité = value;
					this.SendPropertyChanged("quantité");
					this.OnquantitéChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idPoste", DbType="Int NOT NULL")]
		public int idPoste
		{
			get
			{
				return this._idPoste;
			}
			set
			{
				if ((this._idPoste != value))
				{
					if (this._Poste.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidPosteChanging(value);
					this.SendPropertyChanging();
					this._idPoste = value;
					this.SendPropertyChanged("idPoste");
					this.OnidPosteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Poste_Materiel", Storage="_Poste", ThisKey="idPoste", OtherKey="idPoste", IsForeignKey=true)]
		public Poste Poste
		{
			get
			{
				return this._Poste.Entity;
			}
			set
			{
				Poste previousValue = this._Poste.Entity;
				if (((previousValue != value) 
							|| (this._Poste.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Poste.Entity = null;
						previousValue.Materiel.Remove(this);
					}
					this._Poste.Entity = value;
					if ((value != null))
					{
						value.Materiel.Add(this);
						this._idPoste = value.idPoste;
					}
					else
					{
						this._idPoste = default(int);
					}
					this.SendPropertyChanged("Poste");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Personnel")]
	public partial class Personnel : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idPersonnel;
		
		private string _nomPersonnel;
		
		private string _prenomPersonnel;
		
		private System.DateTime _dateNaissance;
		
		private string _email;
		
		private string _telephone;
		
		private string _specialisation;
		
		private string _password;
		
		private string _libelRole;
		
		private System.Nullable<int> _idPoste;
		
		private int _idFestival;
		
		private EntitySet<Demande> _Demande;
		
		private EntitySet<Salaire> _Salaire;
		
		private EntityRef<Festival> _Festival;
		
		private EntityRef<Poste> _Poste;
		
    #region Définitions de méthodes d'extensibilité
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidPersonnelChanging(int value);
    partial void OnidPersonnelChanged();
    partial void OnnomPersonnelChanging(string value);
    partial void OnnomPersonnelChanged();
    partial void OnprenomPersonnelChanging(string value);
    partial void OnprenomPersonnelChanged();
    partial void OndateNaissanceChanging(System.DateTime value);
    partial void OndateNaissanceChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OntelephoneChanging(string value);
    partial void OntelephoneChanged();
    partial void OnspecialisationChanging(string value);
    partial void OnspecialisationChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    partial void OnlibelRoleChanging(string value);
    partial void OnlibelRoleChanged();
    partial void OnidPosteChanging(System.Nullable<int> value);
    partial void OnidPosteChanged();
    partial void OnidFestivalChanging(int value);
    partial void OnidFestivalChanged();
    #endregion
		
		public Personnel()
		{
			this._Demande = new EntitySet<Demande>(new Action<Demande>(this.attach_Demande), new Action<Demande>(this.detach_Demande));
			this._Salaire = new EntitySet<Salaire>(new Action<Salaire>(this.attach_Salaire), new Action<Salaire>(this.detach_Salaire));
			this._Festival = default(EntityRef<Festival>);
			this._Poste = default(EntityRef<Poste>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idPersonnel", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idPersonnel
		{
			get
			{
				return this._idPersonnel;
			}
			set
			{
				if ((this._idPersonnel != value))
				{
					this.OnidPersonnelChanging(value);
					this.SendPropertyChanging();
					this._idPersonnel = value;
					this.SendPropertyChanged("idPersonnel");
					this.OnidPersonnelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nomPersonnel", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string nomPersonnel
		{
			get
			{
				return this._nomPersonnel;
			}
			set
			{
				if ((this._nomPersonnel != value))
				{
					this.OnnomPersonnelChanging(value);
					this.SendPropertyChanging();
					this._nomPersonnel = value;
					this.SendPropertyChanged("nomPersonnel");
					this.OnnomPersonnelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_prenomPersonnel", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string prenomPersonnel
		{
			get
			{
				return this._prenomPersonnel;
			}
			set
			{
				if ((this._prenomPersonnel != value))
				{
					this.OnprenomPersonnelChanging(value);
					this.SendPropertyChanging();
					this._prenomPersonnel = value;
					this.SendPropertyChanged("prenomPersonnel");
					this.OnprenomPersonnelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dateNaissance", DbType="DateTime NOT NULL")]
		public System.DateTime dateNaissance
		{
			get
			{
				return this._dateNaissance;
			}
			set
			{
				if ((this._dateNaissance != value))
				{
					this.OndateNaissanceChanging(value);
					this.SendPropertyChanging();
					this._dateNaissance = value;
					this.SendPropertyChanged("dateNaissance");
					this.OndateNaissanceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telephone", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string telephone
		{
			get
			{
				return this._telephone;
			}
			set
			{
				if ((this._telephone != value))
				{
					this.OntelephoneChanging(value);
					this.SendPropertyChanging();
					this._telephone = value;
					this.SendPropertyChanged("telephone");
					this.OntelephoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_specialisation", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string specialisation
		{
			get
			{
				return this._specialisation;
			}
			set
			{
				if ((this._specialisation != value))
				{
					this.OnspecialisationChanging(value);
					this.SendPropertyChanging();
					this._specialisation = value;
					this.SendPropertyChanged("specialisation");
					this.OnspecialisationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this.OnpasswordChanging(value);
					this.SendPropertyChanging();
					this._password = value;
					this.SendPropertyChanged("password");
					this.OnpasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_libelRole", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string libelRole
		{
			get
			{
				return this._libelRole;
			}
			set
			{
				if ((this._libelRole != value))
				{
					this.OnlibelRoleChanging(value);
					this.SendPropertyChanging();
					this._libelRole = value;
					this.SendPropertyChanged("libelRole");
					this.OnlibelRoleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idPoste", DbType="Int")]
		public System.Nullable<int> idPoste
		{
			get
			{
				return this._idPoste;
			}
			set
			{
				if ((this._idPoste != value))
				{
					if (this._Poste.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidPosteChanging(value);
					this.SendPropertyChanging();
					this._idPoste = value;
					this.SendPropertyChanged("idPoste");
					this.OnidPosteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idFestival", DbType="Int NOT NULL")]
		public int idFestival
		{
			get
			{
				return this._idFestival;
			}
			set
			{
				if ((this._idFestival != value))
				{
					if (this._Festival.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidFestivalChanging(value);
					this.SendPropertyChanging();
					this._idFestival = value;
					this.SendPropertyChanged("idFestival");
					this.OnidFestivalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Personnel_Demande", Storage="_Demande", ThisKey="idPersonnel", OtherKey="idPersonnel")]
		public EntitySet<Demande> Demande
		{
			get
			{
				return this._Demande;
			}
			set
			{
				this._Demande.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Personnel_Salaire", Storage="_Salaire", ThisKey="idPersonnel", OtherKey="idPersonnel")]
		public EntitySet<Salaire> Salaire
		{
			get
			{
				return this._Salaire;
			}
			set
			{
				this._Salaire.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Festival_Personnel", Storage="_Festival", ThisKey="idFestival", OtherKey="idFestival", IsForeignKey=true)]
		public Festival Festival
		{
			get
			{
				return this._Festival.Entity;
			}
			set
			{
				Festival previousValue = this._Festival.Entity;
				if (((previousValue != value) 
							|| (this._Festival.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Festival.Entity = null;
						previousValue.Personnel.Remove(this);
					}
					this._Festival.Entity = value;
					if ((value != null))
					{
						value.Personnel.Add(this);
						this._idFestival = value.idFestival;
					}
					else
					{
						this._idFestival = default(int);
					}
					this.SendPropertyChanged("Festival");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Poste_Personnel", Storage="_Poste", ThisKey="idPoste", OtherKey="idPoste", IsForeignKey=true)]
		public Poste Poste
		{
			get
			{
				return this._Poste.Entity;
			}
			set
			{
				Poste previousValue = this._Poste.Entity;
				if (((previousValue != value) 
							|| (this._Poste.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Poste.Entity = null;
						previousValue.Personnel.Remove(this);
					}
					this._Poste.Entity = value;
					if ((value != null))
					{
						value.Personnel.Add(this);
						this._idPoste = value.idPoste;
					}
					else
					{
						this._idPoste = default(Nullable<int>);
					}
					this.SendPropertyChanged("Poste");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Demande(Demande entity)
		{
			this.SendPropertyChanging();
			entity.Personnel = this;
		}
		
		private void detach_Demande(Demande entity)
		{
			this.SendPropertyChanging();
			entity.Personnel = null;
		}
		
		private void attach_Salaire(Salaire entity)
		{
			this.SendPropertyChanging();
			entity.Personnel = this;
		}
		
		private void detach_Salaire(Salaire entity)
		{
			this.SendPropertyChanging();
			entity.Personnel = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Poste")]
	public partial class Poste : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idPoste;
		
		private string _nomPoste;
		
		private string _description;
		
		private System.Nullable<decimal> _budgetDepart;
		
		private System.Nullable<decimal> _budgetActuel;
		
		private int _idFestival;
		
		private EntitySet<Materiel> _Materiel;
		
		private EntitySet<Personnel> _Personnel;
		
		private EntitySet<Revenu> _Revenu;
		
    #region Définitions de méthodes d'extensibilité
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidPosteChanging(int value);
    partial void OnidPosteChanged();
    partial void OnnomPosteChanging(string value);
    partial void OnnomPosteChanged();
    partial void OndescriptionChanging(string value);
    partial void OndescriptionChanged();
    partial void OnbudgetDepartChanging(System.Nullable<decimal> value);
    partial void OnbudgetDepartChanged();
    partial void OnbudgetActuelChanging(System.Nullable<decimal> value);
    partial void OnbudgetActuelChanged();
    partial void OnidFestivalChanging(int value);
    partial void OnidFestivalChanged();
    #endregion
		
		public Poste()
		{
			this._Materiel = new EntitySet<Materiel>(new Action<Materiel>(this.attach_Materiel), new Action<Materiel>(this.detach_Materiel));
			this._Personnel = new EntitySet<Personnel>(new Action<Personnel>(this.attach_Personnel), new Action<Personnel>(this.detach_Personnel));
			this._Revenu = new EntitySet<Revenu>(new Action<Revenu>(this.attach_Revenu), new Action<Revenu>(this.detach_Revenu));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idPoste", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idPoste
		{
			get
			{
				return this._idPoste;
			}
			set
			{
				if ((this._idPoste != value))
				{
					this.OnidPosteChanging(value);
					this.SendPropertyChanging();
					this._idPoste = value;
					this.SendPropertyChanged("idPoste");
					this.OnidPosteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nomPoste", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string nomPoste
		{
			get
			{
				return this._nomPoste;
			}
			set
			{
				if ((this._nomPoste != value))
				{
					this.OnnomPosteChanging(value);
					this.SendPropertyChanging();
					this._nomPoste = value;
					this.SendPropertyChanged("nomPoste");
					this.OnnomPosteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_description", DbType="NVarChar(50)")]
		public string description
		{
			get
			{
				return this._description;
			}
			set
			{
				if ((this._description != value))
				{
					this.OndescriptionChanging(value);
					this.SendPropertyChanging();
					this._description = value;
					this.SendPropertyChanged("description");
					this.OndescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_budgetDepart", DbType="Money")]
		public System.Nullable<decimal> budgetDepart
		{
			get
			{
				return this._budgetDepart;
			}
			set
			{
				if ((this._budgetDepart != value))
				{
					this.OnbudgetDepartChanging(value);
					this.SendPropertyChanging();
					this._budgetDepart = value;
					this.SendPropertyChanged("budgetDepart");
					this.OnbudgetDepartChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_budgetActuel", DbType="Money")]
		public System.Nullable<decimal> budgetActuel
		{
			get
			{
				return this._budgetActuel;
			}
			set
			{
				if ((this._budgetActuel != value))
				{
					this.OnbudgetActuelChanging(value);
					this.SendPropertyChanging();
					this._budgetActuel = value;
					this.SendPropertyChanged("budgetActuel");
					this.OnbudgetActuelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idFestival", DbType="Int NOT NULL")]
		public int idFestival
		{
			get
			{
				return this._idFestival;
			}
			set
			{
				if ((this._idFestival != value))
				{
					this.OnidFestivalChanging(value);
					this.SendPropertyChanging();
					this._idFestival = value;
					this.SendPropertyChanged("idFestival");
					this.OnidFestivalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Poste_Materiel", Storage="_Materiel", ThisKey="idPoste", OtherKey="idPoste")]
		public EntitySet<Materiel> Materiel
		{
			get
			{
				return this._Materiel;
			}
			set
			{
				this._Materiel.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Poste_Personnel", Storage="_Personnel", ThisKey="idPoste", OtherKey="idPoste")]
		public EntitySet<Personnel> Personnel
		{
			get
			{
				return this._Personnel;
			}
			set
			{
				this._Personnel.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Poste_Revenu", Storage="_Revenu", ThisKey="idPoste", OtherKey="idPoste")]
		public EntitySet<Revenu> Revenu
		{
			get
			{
				return this._Revenu;
			}
			set
			{
				this._Revenu.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Materiel(Materiel entity)
		{
			this.SendPropertyChanging();
			entity.Poste = this;
		}
		
		private void detach_Materiel(Materiel entity)
		{
			this.SendPropertyChanging();
			entity.Poste = null;
		}
		
		private void attach_Personnel(Personnel entity)
		{
			this.SendPropertyChanging();
			entity.Poste = this;
		}
		
		private void detach_Personnel(Personnel entity)
		{
			this.SendPropertyChanging();
			entity.Poste = null;
		}
		
		private void attach_Revenu(Revenu entity)
		{
			this.SendPropertyChanging();
			entity.Poste = this;
		}
		
		private void detach_Revenu(Revenu entity)
		{
			this.SendPropertyChanging();
			entity.Poste = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Revenu")]
	public partial class Revenu : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idRevenu;
		
		private string _description;
		
		private decimal _montant;
		
		private int _idPoste;
		
		private EntityRef<Poste> _Poste;
		
    #region Définitions de méthodes d'extensibilité
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidRevenuChanging(int value);
    partial void OnidRevenuChanged();
    partial void OndescriptionChanging(string value);
    partial void OndescriptionChanged();
    partial void OnmontantChanging(decimal value);
    partial void OnmontantChanged();
    partial void OnidPosteChanging(int value);
    partial void OnidPosteChanged();
    #endregion
		
		public Revenu()
		{
			this._Poste = default(EntityRef<Poste>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idRevenu", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idRevenu
		{
			get
			{
				return this._idRevenu;
			}
			set
			{
				if ((this._idRevenu != value))
				{
					this.OnidRevenuChanging(value);
					this.SendPropertyChanging();
					this._idRevenu = value;
					this.SendPropertyChanged("idRevenu");
					this.OnidRevenuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_description", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string description
		{
			get
			{
				return this._description;
			}
			set
			{
				if ((this._description != value))
				{
					this.OndescriptionChanging(value);
					this.SendPropertyChanging();
					this._description = value;
					this.SendPropertyChanged("description");
					this.OndescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_montant", DbType="Money NOT NULL")]
		public decimal montant
		{
			get
			{
				return this._montant;
			}
			set
			{
				if ((this._montant != value))
				{
					this.OnmontantChanging(value);
					this.SendPropertyChanging();
					this._montant = value;
					this.SendPropertyChanged("montant");
					this.OnmontantChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idPoste", DbType="Int NOT NULL")]
		public int idPoste
		{
			get
			{
				return this._idPoste;
			}
			set
			{
				if ((this._idPoste != value))
				{
					if (this._Poste.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidPosteChanging(value);
					this.SendPropertyChanging();
					this._idPoste = value;
					this.SendPropertyChanged("idPoste");
					this.OnidPosteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Poste_Revenu", Storage="_Poste", ThisKey="idPoste", OtherKey="idPoste", IsForeignKey=true)]
		public Poste Poste
		{
			get
			{
				return this._Poste.Entity;
			}
			set
			{
				Poste previousValue = this._Poste.Entity;
				if (((previousValue != value) 
							|| (this._Poste.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Poste.Entity = null;
						previousValue.Revenu.Remove(this);
					}
					this._Poste.Entity = value;
					if ((value != null))
					{
						value.Revenu.Add(this);
						this._idPoste = value.idPoste;
					}
					else
					{
						this._idPoste = default(int);
					}
					this.SendPropertyChanged("Poste");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Salaire")]
	public partial class Salaire : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idSalaire;
		
		private decimal _salaireHoraire;
		
		private int _nbrHeure;
		
		private int _idPersonnel;
		
		private EntityRef<Personnel> _Personnel;
		
    #region Définitions de méthodes d'extensibilité
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidSalaireChanging(int value);
    partial void OnidSalaireChanged();
    partial void OnsalaireHoraireChanging(decimal value);
    partial void OnsalaireHoraireChanged();
    partial void OnnbrHeureChanging(int value);
    partial void OnnbrHeureChanged();
    partial void OnidPersonnelChanging(int value);
    partial void OnidPersonnelChanged();
    #endregion
		
		public Salaire()
		{
			this._Personnel = default(EntityRef<Personnel>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idSalaire", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idSalaire
		{
			get
			{
				return this._idSalaire;
			}
			set
			{
				if ((this._idSalaire != value))
				{
					this.OnidSalaireChanging(value);
					this.SendPropertyChanging();
					this._idSalaire = value;
					this.SendPropertyChanged("idSalaire");
					this.OnidSalaireChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_salaireHoraire", DbType="Money NOT NULL")]
		public decimal salaireHoraire
		{
			get
			{
				return this._salaireHoraire;
			}
			set
			{
				if ((this._salaireHoraire != value))
				{
					this.OnsalaireHoraireChanging(value);
					this.SendPropertyChanging();
					this._salaireHoraire = value;
					this.SendPropertyChanged("salaireHoraire");
					this.OnsalaireHoraireChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nbrHeure", DbType="Int NOT NULL")]
		public int nbrHeure
		{
			get
			{
				return this._nbrHeure;
			}
			set
			{
				if ((this._nbrHeure != value))
				{
					this.OnnbrHeureChanging(value);
					this.SendPropertyChanging();
					this._nbrHeure = value;
					this.SendPropertyChanged("nbrHeure");
					this.OnnbrHeureChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idPersonnel", DbType="Int NOT NULL")]
		public int idPersonnel
		{
			get
			{
				return this._idPersonnel;
			}
			set
			{
				if ((this._idPersonnel != value))
				{
					if (this._Personnel.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidPersonnelChanging(value);
					this.SendPropertyChanging();
					this._idPersonnel = value;
					this.SendPropertyChanged("idPersonnel");
					this.OnidPersonnelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Personnel_Salaire", Storage="_Personnel", ThisKey="idPersonnel", OtherKey="idPersonnel", IsForeignKey=true)]
		public Personnel Personnel
		{
			get
			{
				return this._Personnel.Entity;
			}
			set
			{
				Personnel previousValue = this._Personnel.Entity;
				if (((previousValue != value) 
							|| (this._Personnel.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Personnel.Entity = null;
						previousValue.Salaire.Remove(this);
					}
					this._Personnel.Entity = value;
					if ((value != null))
					{
						value.Salaire.Add(this);
						this._idPersonnel = value.idPersonnel;
					}
					else
					{
						this._idPersonnel = default(int);
					}
					this.SendPropertyChanged("Personnel");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class AfficherPosteResult
	{
		
		private int _idPoste;
		
		private string _nomPoste;
		
		private string _description;
		
		private System.Nullable<decimal> _budgetDepart;
		
		private System.Nullable<decimal> _budgetActuel;
		
		private int _idFestival;
		
		public AfficherPosteResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idPoste", DbType="Int NOT NULL")]
		public int idPoste
		{
			get
			{
				return this._idPoste;
			}
			set
			{
				if ((this._idPoste != value))
				{
					this._idPoste = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nomPoste", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string nomPoste
		{
			get
			{
				return this._nomPoste;
			}
			set
			{
				if ((this._nomPoste != value))
				{
					this._nomPoste = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_description", DbType="NVarChar(50)")]
		public string description
		{
			get
			{
				return this._description;
			}
			set
			{
				if ((this._description != value))
				{
					this._description = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_budgetDepart", DbType="Money")]
		public System.Nullable<decimal> budgetDepart
		{
			get
			{
				return this._budgetDepart;
			}
			set
			{
				if ((this._budgetDepart != value))
				{
					this._budgetDepart = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_budgetActuel", DbType="Money")]
		public System.Nullable<decimal> budgetActuel
		{
			get
			{
				return this._budgetActuel;
			}
			set
			{
				if ((this._budgetActuel != value))
				{
					this._budgetActuel = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idFestival", DbType="Int NOT NULL")]
		public int idFestival
		{
			get
			{
				return this._idFestival;
			}
			set
			{
				if ((this._idFestival != value))
				{
					this._idFestival = value;
				}
			}
		}
	}
	
	public partial class GetAllMaterielResult
	{
		
		private int _idMateriel;
		
		private string _nom;
		
		private decimal _prix;
		
		private int _quantité;
		
		private int _idPoste;
		
		public GetAllMaterielResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idMateriel", DbType="Int NOT NULL")]
		public int idMateriel
		{
			get
			{
				return this._idMateriel;
			}
			set
			{
				if ((this._idMateriel != value))
				{
					this._idMateriel = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nom", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string nom
		{
			get
			{
				return this._nom;
			}
			set
			{
				if ((this._nom != value))
				{
					this._nom = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_prix", DbType="Money NOT NULL")]
		public decimal prix
		{
			get
			{
				return this._prix;
			}
			set
			{
				if ((this._prix != value))
				{
					this._prix = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_quantité", DbType="Int NOT NULL")]
		public int quantité
		{
			get
			{
				return this._quantité;
			}
			set
			{
				if ((this._quantité != value))
				{
					this._quantité = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idPoste", DbType="Int NOT NULL")]
		public int idPoste
		{
			get
			{
				return this._idPoste;
			}
			set
			{
				if ((this._idPoste != value))
				{
					this._idPoste = value;
				}
			}
		}
	}
	
	public partial class GetAllParticipantResult
	{
		
		private int _idPersonnel;
		
		private string _nomPersonnel;
		
		private string _prenomPersonnel;
		
		private System.DateTime _dateNaissance;
		
		private string _email;
		
		private string _telephone;
		
		private string _specialisation;
		
		private string _password;
		
		private string _libelRole;
		
		private System.Nullable<int> _idPoste;
		
		private int _idFestival;
		
		private int _idSalaire;
		
		private decimal _salaireHoraire;
		
		private int _nbrHeure;
		
		private int _idPersonnel1;
		
		public GetAllParticipantResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idPersonnel", DbType="Int NOT NULL")]
		public int idPersonnel
		{
			get
			{
				return this._idPersonnel;
			}
			set
			{
				if ((this._idPersonnel != value))
				{
					this._idPersonnel = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nomPersonnel", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string nomPersonnel
		{
			get
			{
				return this._nomPersonnel;
			}
			set
			{
				if ((this._nomPersonnel != value))
				{
					this._nomPersonnel = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_prenomPersonnel", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string prenomPersonnel
		{
			get
			{
				return this._prenomPersonnel;
			}
			set
			{
				if ((this._prenomPersonnel != value))
				{
					this._prenomPersonnel = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dateNaissance", DbType="DateTime NOT NULL")]
		public System.DateTime dateNaissance
		{
			get
			{
				return this._dateNaissance;
			}
			set
			{
				if ((this._dateNaissance != value))
				{
					this._dateNaissance = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this._email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telephone", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string telephone
		{
			get
			{
				return this._telephone;
			}
			set
			{
				if ((this._telephone != value))
				{
					this._telephone = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_specialisation", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string specialisation
		{
			get
			{
				return this._specialisation;
			}
			set
			{
				if ((this._specialisation != value))
				{
					this._specialisation = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this._password = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_libelRole", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string libelRole
		{
			get
			{
				return this._libelRole;
			}
			set
			{
				if ((this._libelRole != value))
				{
					this._libelRole = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idPoste", DbType="Int")]
		public System.Nullable<int> idPoste
		{
			get
			{
				return this._idPoste;
			}
			set
			{
				if ((this._idPoste != value))
				{
					this._idPoste = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idFestival", DbType="Int NOT NULL")]
		public int idFestival
		{
			get
			{
				return this._idFestival;
			}
			set
			{
				if ((this._idFestival != value))
				{
					this._idFestival = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idSalaire", DbType="Int NOT NULL")]
		public int idSalaire
		{
			get
			{
				return this._idSalaire;
			}
			set
			{
				if ((this._idSalaire != value))
				{
					this._idSalaire = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_salaireHoraire", DbType="Money NOT NULL")]
		public decimal salaireHoraire
		{
			get
			{
				return this._salaireHoraire;
			}
			set
			{
				if ((this._salaireHoraire != value))
				{
					this._salaireHoraire = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nbrHeure", DbType="Int NOT NULL")]
		public int nbrHeure
		{
			get
			{
				return this._nbrHeure;
			}
			set
			{
				if ((this._nbrHeure != value))
				{
					this._nbrHeure = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idPersonnel1", DbType="Int NOT NULL")]
		public int idPersonnel1
		{
			get
			{
				return this._idPersonnel1;
			}
			set
			{
				if ((this._idPersonnel1 != value))
				{
					this._idPersonnel1 = value;
				}
			}
		}
	}
	
	public partial class GetAllRevenuResult
	{
		
		private int _idRevenu;
		
		private string _description;
		
		private decimal _montant;
		
		private int _idPoste;
		
		public GetAllRevenuResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idRevenu", DbType="Int NOT NULL")]
		public int idRevenu
		{
			get
			{
				return this._idRevenu;
			}
			set
			{
				if ((this._idRevenu != value))
				{
					this._idRevenu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_description", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string description
		{
			get
			{
				return this._description;
			}
			set
			{
				if ((this._description != value))
				{
					this._description = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_montant", DbType="Money NOT NULL")]
		public decimal montant
		{
			get
			{
				return this._montant;
			}
			set
			{
				if ((this._montant != value))
				{
					this._montant = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idPoste", DbType="Int NOT NULL")]
		public int idPoste
		{
			get
			{
				return this._idPoste;
			}
			set
			{
				if ((this._idPoste != value))
				{
					this._idPoste = value;
				}
			}
		}
	}
	
	public partial class GetPersonnelOnlyResult
	{
		
		private int _idPersonnel;
		
		private string _nomPersonnel;
		
		private string _prenomPersonnel;
		
		private System.DateTime _dateNaissance;
		
		private string _email;
		
		private string _telephone;
		
		private string _specialisation;
		
		private string _password;
		
		private string _libelRole;
		
		private System.Nullable<int> _idPoste;
		
		private int _idFestival;
		
		public GetPersonnelOnlyResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idPersonnel", DbType="Int NOT NULL")]
		public int idPersonnel
		{
			get
			{
				return this._idPersonnel;
			}
			set
			{
				if ((this._idPersonnel != value))
				{
					this._idPersonnel = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nomPersonnel", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string nomPersonnel
		{
			get
			{
				return this._nomPersonnel;
			}
			set
			{
				if ((this._nomPersonnel != value))
				{
					this._nomPersonnel = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_prenomPersonnel", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string prenomPersonnel
		{
			get
			{
				return this._prenomPersonnel;
			}
			set
			{
				if ((this._prenomPersonnel != value))
				{
					this._prenomPersonnel = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dateNaissance", DbType="DateTime NOT NULL")]
		public System.DateTime dateNaissance
		{
			get
			{
				return this._dateNaissance;
			}
			set
			{
				if ((this._dateNaissance != value))
				{
					this._dateNaissance = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this._email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telephone", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string telephone
		{
			get
			{
				return this._telephone;
			}
			set
			{
				if ((this._telephone != value))
				{
					this._telephone = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_specialisation", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string specialisation
		{
			get
			{
				return this._specialisation;
			}
			set
			{
				if ((this._specialisation != value))
				{
					this._specialisation = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this._password = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_libelRole", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string libelRole
		{
			get
			{
				return this._libelRole;
			}
			set
			{
				if ((this._libelRole != value))
				{
					this._libelRole = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idPoste", DbType="Int")]
		public System.Nullable<int> idPoste
		{
			get
			{
				return this._idPoste;
			}
			set
			{
				if ((this._idPoste != value))
				{
					this._idPoste = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idFestival", DbType="Int NOT NULL")]
		public int idFestival
		{
			get
			{
				return this._idFestival;
			}
			set
			{
				if ((this._idFestival != value))
				{
					this._idFestival = value;
				}
			}
		}
	}
	
	public partial class GetRespAndPosteResult
	{
		
		private int _idPersonnel;
		
		private string _nomPersonnel;
		
		private string _prenomPersonnel;
		
		private System.DateTime _dateNaissance;
		
		private string _email;
		
		private string _telephone;
		
		private string _specialisation;
		
		private string _password;
		
		private string _libelRole;
		
		private System.Nullable<int> _idPoste;
		
		private int _idFestival;
		
		private int _idPoste1;
		
		private string _nomPoste;
		
		private string _description;
		
		private System.Nullable<decimal> _budgetDepart;
		
		private System.Nullable<decimal> _budgetActuel;
		
		private int _idFestival1;
		
		public GetRespAndPosteResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idPersonnel", DbType="Int NOT NULL")]
		public int idPersonnel
		{
			get
			{
				return this._idPersonnel;
			}
			set
			{
				if ((this._idPersonnel != value))
				{
					this._idPersonnel = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nomPersonnel", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string nomPersonnel
		{
			get
			{
				return this._nomPersonnel;
			}
			set
			{
				if ((this._nomPersonnel != value))
				{
					this._nomPersonnel = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_prenomPersonnel", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string prenomPersonnel
		{
			get
			{
				return this._prenomPersonnel;
			}
			set
			{
				if ((this._prenomPersonnel != value))
				{
					this._prenomPersonnel = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dateNaissance", DbType="DateTime NOT NULL")]
		public System.DateTime dateNaissance
		{
			get
			{
				return this._dateNaissance;
			}
			set
			{
				if ((this._dateNaissance != value))
				{
					this._dateNaissance = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this._email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telephone", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string telephone
		{
			get
			{
				return this._telephone;
			}
			set
			{
				if ((this._telephone != value))
				{
					this._telephone = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_specialisation", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string specialisation
		{
			get
			{
				return this._specialisation;
			}
			set
			{
				if ((this._specialisation != value))
				{
					this._specialisation = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this._password = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_libelRole", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string libelRole
		{
			get
			{
				return this._libelRole;
			}
			set
			{
				if ((this._libelRole != value))
				{
					this._libelRole = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idPoste", DbType="Int")]
		public System.Nullable<int> idPoste
		{
			get
			{
				return this._idPoste;
			}
			set
			{
				if ((this._idPoste != value))
				{
					this._idPoste = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idFestival", DbType="Int NOT NULL")]
		public int idFestival
		{
			get
			{
				return this._idFestival;
			}
			set
			{
				if ((this._idFestival != value))
				{
					this._idFestival = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idPoste1", DbType="Int NOT NULL")]
		public int idPoste1
		{
			get
			{
				return this._idPoste1;
			}
			set
			{
				if ((this._idPoste1 != value))
				{
					this._idPoste1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nomPoste", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string nomPoste
		{
			get
			{
				return this._nomPoste;
			}
			set
			{
				if ((this._nomPoste != value))
				{
					this._nomPoste = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_description", DbType="NVarChar(50)")]
		public string description
		{
			get
			{
				return this._description;
			}
			set
			{
				if ((this._description != value))
				{
					this._description = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_budgetDepart", DbType="Money")]
		public System.Nullable<decimal> budgetDepart
		{
			get
			{
				return this._budgetDepart;
			}
			set
			{
				if ((this._budgetDepart != value))
				{
					this._budgetDepart = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_budgetActuel", DbType="Money")]
		public System.Nullable<decimal> budgetActuel
		{
			get
			{
				return this._budgetActuel;
			}
			set
			{
				if ((this._budgetActuel != value))
				{
					this._budgetActuel = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idFestival1", DbType="Int NOT NULL")]
		public int idFestival1
		{
			get
			{
				return this._idFestival1;
			}
			set
			{
				if ((this._idFestival1 != value))
				{
					this._idFestival1 = value;
				}
			}
		}
	}
	
	public partial class GetSalaireResult
	{
		
		private int _idSalaire;
		
		private decimal _salaireHoraire;
		
		private int _nbrHeure;
		
		private int _idPersonnel;
		
		public GetSalaireResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idSalaire", DbType="Int NOT NULL")]
		public int idSalaire
		{
			get
			{
				return this._idSalaire;
			}
			set
			{
				if ((this._idSalaire != value))
				{
					this._idSalaire = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_salaireHoraire", DbType="Money NOT NULL")]
		public decimal salaireHoraire
		{
			get
			{
				return this._salaireHoraire;
			}
			set
			{
				if ((this._salaireHoraire != value))
				{
					this._salaireHoraire = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nbrHeure", DbType="Int NOT NULL")]
		public int nbrHeure
		{
			get
			{
				return this._nbrHeure;
			}
			set
			{
				if ((this._nbrHeure != value))
				{
					this._nbrHeure = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idPersonnel", DbType="Int NOT NULL")]
		public int idPersonnel
		{
			get
			{
				return this._idPersonnel;
			}
			set
			{
				if ((this._idPersonnel != value))
				{
					this._idPersonnel = value;
				}
			}
		}
	}
	
	public partial class VérificatioCompteExistantResult
	{
		
		private System.Nullable<int> _Column1;
		
		public VérificatioCompteExistantResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="", Storage="_Column1", DbType="Int")]
		public System.Nullable<int> Column1
		{
			get
			{
				return this._Column1;
			}
			set
			{
				if ((this._Column1 != value))
				{
					this._Column1 = value;
				}
			}
		}
	}
	
	public partial class VérificationLoginResult
	{
		
		private int _idPersonnel;
		
		private string _nomPersonnel;
		
		private string _prenomPersonnel;
		
		private System.DateTime _dateNaissance;
		
		private string _email;
		
		private string _telephone;
		
		private string _specialisation;
		
		private string _password;
		
		private string _libelRole;
		
		private System.Nullable<int> _idPoste;
		
		private int _idFestival;
		
		public VérificationLoginResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idPersonnel", DbType="Int NOT NULL")]
		public int idPersonnel
		{
			get
			{
				return this._idPersonnel;
			}
			set
			{
				if ((this._idPersonnel != value))
				{
					this._idPersonnel = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nomPersonnel", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string nomPersonnel
		{
			get
			{
				return this._nomPersonnel;
			}
			set
			{
				if ((this._nomPersonnel != value))
				{
					this._nomPersonnel = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_prenomPersonnel", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string prenomPersonnel
		{
			get
			{
				return this._prenomPersonnel;
			}
			set
			{
				if ((this._prenomPersonnel != value))
				{
					this._prenomPersonnel = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dateNaissance", DbType="DateTime NOT NULL")]
		public System.DateTime dateNaissance
		{
			get
			{
				return this._dateNaissance;
			}
			set
			{
				if ((this._dateNaissance != value))
				{
					this._dateNaissance = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this._email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telephone", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string telephone
		{
			get
			{
				return this._telephone;
			}
			set
			{
				if ((this._telephone != value))
				{
					this._telephone = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_specialisation", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string specialisation
		{
			get
			{
				return this._specialisation;
			}
			set
			{
				if ((this._specialisation != value))
				{
					this._specialisation = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this._password = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_libelRole", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string libelRole
		{
			get
			{
				return this._libelRole;
			}
			set
			{
				if ((this._libelRole != value))
				{
					this._libelRole = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idPoste", DbType="Int")]
		public System.Nullable<int> idPoste
		{
			get
			{
				return this._idPoste;
			}
			set
			{
				if ((this._idPoste != value))
				{
					this._idPoste = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idFestival", DbType="Int NOT NULL")]
		public int idFestival
		{
			get
			{
				return this._idFestival;
			}
			set
			{
				if ((this._idFestival != value))
				{
					this._idFestival = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
