<?xml version="1.0" encoding="utf-8"?><Database Name="GestionFestival" Class="DataContextDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=DESKTOP-73L8O8A;Initial Catalog=GestionFestival;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="GestionFestivalConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Administrateur" Member="Administrateur">
    <Type Name="Administrateur">
      <Column Name="idPers" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="dateFest" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="nomFest" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Personnel_Administrateur" Member="Personnel" ThisKey="idPers" OtherKey="idPers" Type="Personnel" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Comptable" Member="Comptable">
    <Type Name="Comptable">
      <Column Name="idPers" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="budgetDisp" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="salaire" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="idAdmin" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Personnel_Comptable" Member="Personnel" ThisKey="idPers" OtherKey="idPers" Type="Personnel" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Depense" Member="Depense">
    <Type Name="Depense">
      <Column Name="idDepense" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="idPoste" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="totalDepense" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Association Name="Depense_Materiel" Member="Materiel" ThisKey="idDepense" OtherKey="idDepense" Type="Materiel" />
      <Association Name="Depense_Participant" Member="Participant" ThisKey="idDepense" OtherKey="idDepense" Type="Participant" />
      <Association Name="Poste_Depense" Member="Poste" ThisKey="idPoste" OtherKey="idPoste" Type="Poste" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Materiel" Member="Materiel">
    <Type Name="Materiel">
      <Column Name="idMateriel" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nom" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="prix" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="quantité" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="idDepense" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="idPers" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Depense_Materiel" Member="Depense" ThisKey="idDepense" OtherKey="idDepense" Type="Depense" IsForeignKey="true" />
      <Association Name="Responsable_Materiel" Member="Responsable" ThisKey="idPers" OtherKey="idPers" Type="Responsable" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Participant" Member="Participant">
    <Type Name="Participant">
      <Column Name="idPers" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="heureTravail" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="salaire" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="idResp" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="idDepense" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Depense_Participant" Member="Depense" ThisKey="idDepense" OtherKey="idDepense" Type="Depense" IsForeignKey="true" />
      <Association Name="Personnel_Participant" Member="Personnel" ThisKey="idPers" OtherKey="idPers" Type="Personnel" IsForeignKey="true" />
      <Association Name="Responsable_Participant" Member="Responsable" ThisKey="idResp" OtherKey="idPers" Type="Responsable" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Personnel" Member="Personnel">
    <Type Name="Personnel">
      <Column Name="idPers" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nomPers" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="prenomPers" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="dateNaiss" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="email" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="telephone" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="specialisation" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="pass" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Personnel_Administrateur" Member="Administrateur" ThisKey="idPers" OtherKey="idPers" Type="Administrateur" Cardinality="One" />
      <Association Name="Personnel_Comptable" Member="Comptable" ThisKey="idPers" OtherKey="idPers" Type="Comptable" Cardinality="One" />
      <Association Name="Personnel_Participant" Member="Participant" ThisKey="idPers" OtherKey="idPers" Type="Participant" Cardinality="One" />
      <Association Name="Personnel_Responsable" Member="Responsable" ThisKey="idPers" OtherKey="idPers" Type="Responsable" Cardinality="One" />
    </Type>
  </Table>
  <Table Name="dbo.Poste" Member="Poste">
    <Type Name="Poste">
      <Column Name="idPoste" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nomPoste" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="description" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="budgetDepart" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="budgetActuel" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Association Name="Poste_Depense" Member="Depense" ThisKey="idPoste" OtherKey="idPoste" Type="Depense" />
      <Association Name="Poste_Recette" Member="Recette" ThisKey="idPoste" OtherKey="idPoste" Type="Recette" />
      <Association Name="Poste_Responsable" Member="Responsable" ThisKey="idPoste" OtherKey="idPoste" Type="Responsable" />
    </Type>
  </Table>
  <Table Name="dbo.Recette" Member="Recette">
    <Type Name="Recette">
      <Column Name="idRecette" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="totalRec" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="idPoste" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Recette_Revenu" Member="Revenu" ThisKey="idRecette" OtherKey="idRecette" Type="Revenu" />
      <Association Name="Poste_Recette" Member="Poste" ThisKey="idPoste" OtherKey="idPoste" Type="Poste" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Responsable" Member="Responsable">
    <Type Name="Responsable">
      <Column Name="idPers" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="fonction" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="salaireResp" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="idPoste" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Responsable_Materiel" Member="Materiel" ThisKey="idPers" OtherKey="idPers" Type="Materiel" />
      <Association Name="Responsable_Participant" Member="Participant" ThisKey="idPers" OtherKey="idResp" Type="Participant" />
      <Association Name="Responsable_Revenu" Member="Revenu" ThisKey="idPers" OtherKey="idPersonnel" Type="Revenu" />
      <Association Name="Personnel_Responsable" Member="Personnel" ThisKey="idPers" OtherKey="idPers" Type="Personnel" IsForeignKey="true" />
      <Association Name="Poste_Responsable" Member="Poste" ThisKey="idPoste" OtherKey="idPoste" Type="Poste" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Revenu" Member="Revenu">
    <Type Name="Revenu">
      <Column Name="idRevenu" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="description" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="montant" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="idRecette" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="idPersonnel" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Recette_Revenu" Member="Recette" ThisKey="idRecette" OtherKey="idRecette" Type="Recette" IsForeignKey="true" />
      <Association Name="Responsable_Revenu" Member="Responsable" ThisKey="idPersonnel" OtherKey="idPers" Type="Responsable" IsForeignKey="true" />
    </Type>
  </Table>
  <Function Name="dbo.AfficherPoste" Method="AfficherPoste">
    <ElementType Name="AfficherPosteResult">
      <Column Name="idPoste" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="nomPoste" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="description" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="budgetDepart" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="budgetActuel" Type="System.Decimal" DbType="Money" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.AjouterMateriel" Method="AjouterMateriel">
    <Parameter Name="nom" Type="System.String" DbType="NVarChar(20)" />
    <Parameter Name="prix" Type="System.Decimal" DbType="Money" />
    <Parameter Name="qtt" Type="System.Int32" DbType="Int" />
    <Parameter Name="idPers" Type="System.Int32" DbType="Int" />
    <Parameter Name="idPoste" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.AjouterParticipant" Method="AjouterParticipant">
    <Parameter Name="idPers" Type="System.Int32" DbType="Int" />
    <Parameter Name="salaire" Type="System.Decimal" DbType="Money" />
    <Parameter Name="ht" Type="System.Int32" DbType="Int" />
    <Parameter Name="idResp" Type="System.Int32" DbType="Int" />
    <Parameter Name="idPoste" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.AjouterPersonnel" Method="AjouterPersonnel">
    <Parameter Name="nom" Type="System.String" DbType="NVarChar(20)" />
    <Parameter Name="prenom" Type="System.String" DbType="NVarChar(20)" />
    <Parameter Name="dateNaiss" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="email" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="tel" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="spec" Type="System.String" DbType="NVarChar(20)" />
    <Parameter Name="pass" Type="System.String" DbType="NVarChar(20)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.AjouterPoste" Method="AjouterPoste">
    <Parameter Name="nomPoste" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="description" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.AjouterRevenu" Method="AjouterRevenu">
    <Parameter Name="desc" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="montant" Type="System.Decimal" DbType="Money" />
    <Parameter Name="idPers" Type="System.Int32" DbType="Int" />
    <Parameter Name="idPoste" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.DeleteMateriel" Method="DeleteMateriel">
    <Parameter Name="idMat" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.DeleteParticipant" Method="DeleteParticipant">
    <Parameter Name="idPart" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.DeleteRevenu" Method="DeleteRevenu">
    <Parameter Name="idRev" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.GetAllMateriel" Method="GetAllMateriel">
    <Parameter Name="idPers" Type="System.Int32" DbType="Int" />
    <ElementType Name="GetAllMaterielResult">
      <Column Name="idMateriel" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="nom" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="prix" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="quantité" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="idDepense" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="idPers" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetAllParticipant" Method="GetAllParticipant">
    <Parameter Name="idResp" Type="System.Int32" DbType="Int" />
    <ElementType Name="GetAllParticipantResult">
      <Column Name="idPers" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="heureTravail" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="salaire" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="idResp" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="idDepense" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="idPers1" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="nomPers" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="prenomPers" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="dateNaiss" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="email" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="telephone" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="specialisation" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="pass" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetAllRevenu" Method="GetAllRevenu">
    <Parameter Name="idPers" Type="System.Int32" DbType="Int" />
    <ElementType Name="GetAllRevenuResult">
      <Column Name="idRevenu" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="description" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="montant" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="idRecette" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="idPersonnel" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetPersonnelOnly" Method="GetPersonnelOnly">
    <ElementType Name="GetPersonnelOnlyResult">
      <Column Name="idPers" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="nomPers" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="prenomPers" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="dateNaiss" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="email" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="telephone" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="specialisation" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="pass" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetRespAndPoste" Method="GetRespAndPoste">
    <Parameter Name="idPers" Type="System.Int32" DbType="Int" />
    <ElementType Name="GetRespAndPosteResult">
      <Column Name="idPers" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="fonction" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="salaireResp" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="idPoste" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="idAdmin" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="idPoste1" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="nomPoste" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="description" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="budgetDepart" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="budgetActuel" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.isAdmin" Method="isAdmin">
    <Parameter Name="id" Type="System.Int32" DbType="Int" />
    <ElementType Name="isAdminResult">
      <Column Name="idPers" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="dateFest" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="nomFest" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.isCompt" Method="isCompt">
    <Parameter Name="id" Type="System.Int32" DbType="Int" />
    <ElementType Name="isComptResult">
      <Column Name="idPers" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="budgetDisp" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="salaire" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="idAdmin" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.isParticipant" Method="isParticipant">
    <Parameter Name="id" Type="System.Int32" DbType="Int" />
    <ElementType Name="isParticipantResult">
      <Column Name="idPers" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="heureTravail" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="salaire" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="idResp" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="idDepense" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.isResponsable" Method="isResponsable">
    <Parameter Name="id" Type="System.Int32" DbType="Int" />
    <ElementType Name="isResponsableResult">
      <Column Name="idPers" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="fonction" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="salaireResp" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="idPoste" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.ModifierPoste" Method="ModifierPoste">
    <Parameter Name="id" Type="System.Int32" DbType="Int" />
    <Parameter Name="nomPoste" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="description" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SupprimerPoste" Method="SupprimerPoste">
    <Parameter Name="idPoste" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.UpdateMateriel" Method="UpdateMateriel">
    <Parameter Name="nom" Type="System.String" DbType="NVarChar(20)" />
    <Parameter Name="prix" Type="System.Decimal" DbType="Money" />
    <Parameter Name="qtt" Type="System.Int32" DbType="Int" />
    <Parameter Name="idMat" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.UpdateParticipant" Method="UpdateParticipant">
    <Parameter Name="salaire" Type="System.Decimal" DbType="Money" />
    <Parameter Name="ht" Type="System.Int32" DbType="Int" />
    <Parameter Name="idPart" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.UpdateRevenu" Method="UpdateRevenu">
    <Parameter Name="desc" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="montant" Type="System.Decimal" DbType="Money" />
    <Parameter Name="idRev" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.VérificatioCompteExistant" Method="VérificatioCompteExistant">
    <Parameter Name="email" Type="System.String" DbType="NVarChar(50)" />
    <ElementType Name="VérificatioCompteExistantResult">
      <Column Name="" Member="Column1" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.VérificationLogin" Method="VérificationLogin">
    <Parameter Name="email" Type="System.String" DbType="NVarChar(30)" />
    <Parameter Name="pass" Type="System.String" DbType="NVarChar(50)" />
    <ElementType Name="VérificationLoginResult">
      <Column Name="idPers" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="nomPers" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="prenomPers" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="dateNaiss" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="email" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="telephone" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="specialisation" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="pass" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.AfficherPoste" Method="AfficherPoste">
    <ElementType Name="AfficherPosteResult">
      <Column Name="idPoste" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="nomPoste" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="description" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="budgetDepart" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="budgetActuel" Type="System.Decimal" DbType="Money" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>